let startTime = "Начало отказа",
  failCategory = "Категория отказа",
  failKind = "Вид технологического наруш",
  guiltyUnit = "Виновное предприятие",
  failReason = "Причина 2 ур",
  freightTrainsDelayed = "Количество грузовых поездов(по месту)",
  freightTrainsDuration = "Время грузовых поездов(по месту)",
  passTrainsDelayed = "Количество пассажирских поездов(по месту)",
  passTrainsDuration = "Время пассажирских поездов(по месту)",
  subTrainsDelayed = "Количество пригородных поездов(по месту)",
  subTrainsDuration = "Время пригородных поездов(по месту)",
  otherTrainsDelayed = "Количество прочих поездов(по месту)",
  otherTrainsDuration = "Время прочих поездов(по месту)";

export {
  startTime,
  failCategory,
  failKind,
  guiltyUnit,
  failReason,
  freightTrainsDelayed,
  freightTrainsDuration,
  passTrainsDelayed,
  passTrainsDuration,
  subTrainsDelayed,
  subTrainsDuration,
  otherTrainsDelayed,
  otherTrainsDuration,
};
